export const DEFAULT_MISC_FIELDS = [
    { fieldName: "Birthday", type: "text" },
    { fieldName: "Co-owner Birthday", type: "text" },
    { fieldName: "Home Close Date", type: "text" },
    { fieldName: "Listing Status", type: "text" },
    { fieldName: "Status Change Date", type: "text" },
    { fieldName: "Tax Name", type: "text" },
    { fieldName: "List Price", type: "text" },
    { fieldName: "Days On Market", type: "text" },
    { fieldName: "List Date", type: "text" },
    { fieldName: "MLS ID", type: "text" },
    { fieldName: "Property Type", type: "text" },
    { fieldName: "Bedrooms", type: "text" },
    { fieldName: "Bathrooms", type: "text" },
    { fieldName: "Square Footage", type: "text" },
    { fieldName: "Year Built", type: "text" },
    { fieldName: "Agent Phone Number", type: "text" },
    { fieldName: "Agent Company", type: "text" },
    { fieldName: "Agent Name", type: "text" },
    { fieldName: "Agent Remarks", type: "text" },
    { fieldName: "Notes", type: "text" },
    { fieldName: "County", type: "text" },
    { fieldName: "Delinquent Amount", type: "text" },
    { fieldName: "Mortgage Holder", type: "text" },
    { fieldName: "Auction Min Bid", type: "text" },
    { fieldName: "Pre-Foreclosure Type", type: "text" },
    { fieldName: "Attorney Name", type: "text" },
    { fieldName: "Date Recorded", type: "text" },
    { fieldName: "Acres", type: "text" },
    { fieldName: "Auction Deposit", type: "text" },
    { fieldName: "Price", type: "text" },
    { fieldName: "Estimated Value", type: "text" },
    { fieldName: "Lot Size", type: "text" },
    { fieldName: "Taxes", type: "text" },
    { fieldName: "Tax Year", type: "text" },
    { fieldName: "Subdivision", type: "text" },
    { fieldName: "Listing Title", type: "text" },
    { fieldName: "Listing URL", type: "text" },
    { fieldName: "Assessed Value", type: "text" },
    { fieldName: "Last Sale Amount", type: "text" },
    { fieldName: "Last Sale Date", type: "text" },
    { fieldName: "Living Square Feet", type: "text" },
    { fieldName: "APN", type: "text" },
    { fieldName: "Occupied", type: "text" },
    { fieldName: "Agent Email", type: "text" },
    { fieldName: "Auction Date", type: "text" },
    { fieldName: "Auction Location", type: "text" },
    { fieldName: "Loan Amount", type: "text" },
    { fieldName: "Attorney Phone", type: "text" },
    { fieldName: "Mortgage Date", type: "text" },
    { fieldName: "Phone 3", type: "text" }
];
